const PDFDocument = require('pdfkit');
const prisma = require('../../config/db');
const ApiError = require('../../utils/ApiError');

const RESUME_INCLUDE = {
  template: true,
  education: { orderBy: { display_order: 'asc' } },
  workExperience: { orderBy: { display_order: 'asc' } },
  projects: { orderBy: { display_order: 'asc' } },
  certifications: { orderBy: { display_order: 'asc' } },
  languages: { orderBy: { display_order: 'asc' } },
  resumeSkills: { orderBy: { display_order: 'asc' }, include: { skill: true } },
  user: { select: { full_name: true, email: true } },
};

/**
 * Streams a PDF of the resume to the HTTP response.
 */
const exportPdf = async (resumeId, userId, isAdmin, res) => {
  const resume = await prisma.resume.findFirst({
    where: { id: resumeId, deletedAt: null },
    include: RESUME_INCLUDE,
  });

  if (!resume) throw ApiError.notFound('Resume not found');
  if (!isAdmin && resume.user_id !== userId) throw ApiError.forbidden('Access denied');

  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${_sanitizeFilename(resume.title)}.pdf"`);

  doc.pipe(res);

  // ── Header ──────────────────────────────────────────────
  doc.fontSize(22).font('Helvetica-Bold').text(resume.user?.full_name || resume.title, { align: 'center' });
  doc.fontSize(10).font('Helvetica').text(resume.user?.email || '', { align: 'center' });
  doc.moveDown(0.5);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#cccccc').stroke();
  doc.moveDown(0.5);

  // ── Education ───────────────────────────────────────────
  if (resume.education.length > 0) {
    _sectionHeader(doc, 'EDUCATION');
    resume.education.forEach((e) => {
      doc.fontSize(11).font('Helvetica-Bold').text(`${e.degree}${e.field_of_study ? ` in ${e.field_of_study}` : ''}`);
      doc.fontSize(10).font('Helvetica').text(`${e.institution}  |  ${_fmt(e.start_date)} – ${e.end_date ? _fmt(e.end_date) : 'Present'}`);
      if (e.gpa) doc.text(`GPA: ${e.gpa}`);
      doc.moveDown(0.4);
    });
  }

  // ── Work Experience ─────────────────────────────────────
  if (resume.workExperience.length > 0) {
    _sectionHeader(doc, 'WORK EXPERIENCE');
    resume.workExperience.forEach((w) => {
      doc.fontSize(11).font('Helvetica-Bold').text(w.position);
      doc.fontSize(10).font('Helvetica').text(`${w.company}${w.location ? ` • ${w.location}` : ''}  |  ${_fmt(w.start_date)} – ${w.is_current ? 'Present' : _fmt(w.end_date)}`);
      if (w.description) doc.text(w.description, { width: 480 });
      doc.moveDown(0.4);
    });
  }

  // ── Skills ──────────────────────────────────────────────
  if (resume.resumeSkills.length > 0) {
    _sectionHeader(doc, 'SKILLS');
    const skills = resume.resumeSkills.map((rs) => `${rs.skill.name} (${rs.proficiency_level})`).join('  •  ');
    doc.fontSize(10).font('Helvetica').text(skills, { width: 480 });
    doc.moveDown(0.5);
  }

  // ── Projects ────────────────────────────────────────────
  if (resume.projects.length > 0) {
    _sectionHeader(doc, 'PROJECTS');
    resume.projects.forEach((p) => {
      doc.fontSize(11).font('Helvetica-Bold').text(p.title);
      if (p.description) doc.fontSize(10).font('Helvetica').text(p.description, { width: 480 });
      if (p.url) doc.fontSize(9).fillColor('blue').text(p.url, { link: p.url }).fillColor('black');
      doc.moveDown(0.4);
    });
  }

  // ── Certifications ──────────────────────────────────────
  if (resume.certifications.length > 0) {
    _sectionHeader(doc, 'CERTIFICATIONS');
    resume.certifications.forEach((c) => {
      doc.fontSize(11).font('Helvetica-Bold').text(c.name);
      doc.fontSize(10).font('Helvetica').text(`${c.issuing_org}  |  Issued: ${_fmt(c.issue_date)}`);
      if (c.expiry_date) doc.text(`Expires: ${_fmt(c.expiry_date)}`);
      doc.moveDown(0.4);
    });
  }

  // ── Languages ───────────────────────────────────────────
  if (resume.languages.length > 0) {
    _sectionHeader(doc, 'LANGUAGES');
    const langs = resume.languages.map((l) => `${l.language} (${l.proficiency})`).join('  •  ');
    doc.fontSize(10).font('Helvetica').text(langs);
    doc.moveDown(0.5);
  }

  // ── Footer ──────────────────────────────────────────────
  doc.fontSize(8).fillColor('#999999').text(`Generated by Resume Builder • ${new Date().toLocaleDateString()}`, { align: 'center' });

  doc.end();

  // Audit log (non-blocking)
  prisma.auditLog.create({
    data: {
      entity_type: 'Resume',
      entity_id: resumeId,
      action: 'exported',
      performed_by: userId,
    },
  }).catch(() => {});
};

const _sectionHeader = (doc, title) => {
  doc.fontSize(12).font('Helvetica-Bold').fillColor('#2c3e50').text(title);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#2c3e50').stroke();
  doc.fillColor('black').moveDown(0.3);
};

const _fmt = (date) => {
  if (!date) return '';
  return new Date(date).toLocaleDateString('en-US', { month: 'short', year: 'numeric' });
};

const _sanitizeFilename = (name) => name.replace(/[^a-z0-9_\-]/gi, '_').substring(0, 60);

module.exports = { exportPdf };
